baseURL = 'https://cee-r.github.io/'
languageCode = 'en-us'
title = 'Mario Kart Champions'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  base_path = '/mk-champs'

# [taxonomies]
# Use singular rather than plural for default taxonomies
# mode = "mode"
# game = "game"